### ISSUE TITLE
Date de fin < Date de début

### ISSUE THREAD

**Issue by Shuyuu** [anthonybocci/BDTLN#10]
Si on met une date de fin situé avant la date du début lors de la création d'un projet, ça nous met un message d'erreur, mais sans préciser pourquoi, c'est un truc du genre "project couldn't be saved" que ça dit, un p'tit "Date de fin situé avant la date du début" ou un truc du genre serait plus approprié j'pense :p

**Comment by anthonybocci** [comment]
J'ai rajouté un message qui dit que la date de fin doit être supérieure à la date de début, dans un petit cadre rouge.
Tu me diras si ça suffit.
