### ISSUE TITLE
plusieurs problèmes sur la page de profil

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#11]
- La biographie française et anglaise sont toujours affichées quelque soit la langue choisie.
-Quand on édite son profil, le texte pour supprimer la photo est toujours en anglais "just delete my photo"  même si la langue choisie est le français (d'ailleurs pourquoi ce "just", pourquoi pas juste "delete my photo" ?)
-Sur la page d'édition du profil, pour ajouter une photo il y a écrit "photo " et "file" quelque soit la langue choisie (alors que "file" est un terme anglais), et pourquoi pas juste "photo" ?

**Comment by anthonybocci** [comment]
Désormais il n'y a plus qu'une seule biographie d'affichée sur le profile selon si on est en FR ou EN.
Ensuite, pour éditer le profil j'ai enlevé le "File" et désormais il n'y a plus que "Photo".
Pour finir, j'ai remplacer le "Just delete my photo" qui signifiait qu'on voulait enlever sa photo sans la changer, par "Delete my photo".
Tu me diras ce que tu en penses.
