### ISSUE TITLE
bouton ajouter un axe ne fonctionne pas

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#14]
Pour moi (benoit), le bouton "ajouter" en bas de la page pour ajouter un axe ne fonctionne pas. Il ne donne pas d'erreur, mais ne fait rien. Par contre celui de "ajouter projet" fonctionne.

**Comment by anthonybocci** [comment]
Je l'ai essayé une première fois, ça a fonctionné normalement. Je l'ai essayé une seconde fois, et il me demande de compléter un champ.. Sauf qu'il pointe en dehors de la fenêtre. Je vais voir ça.

**Comment by anthonybocci** [comment]
C'est tinyMCE qui pour une raison obscure nous fait boguer car le navigateur croit que le les textarea sont vides même lorsqu'ils ne le sont pas.
Donc j'ai laissé la vérification du côté du serveur mais du côté client j'ai retiré l'attribut required
