### ISSUE TITLE
erreur suppression d'un axe

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#15]
Quand on supprime un axe, on doit confirmer en choisissant "oui" ou "non", puis cliquer sur "supprimer". Quand je choisis "non" et que je clique, j'obtiens l'erreur suivante : 
Some mandatory parameters are missing ("slug") to generate a URL for route "bdtln_axe_display_axe".
500 Internal Server Error - MissingMandatoryParametersException

**Comment by anthonybocci** [comment]
J'avais oublié de donner le paramètre slug lors de la redirection, c'est corrigé
