### ISSUE TITLE
remplacer "Ce projet contient déjà tous les axes"

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#16]
Quand un projet contient tous les axes, s'affiche "Ce projet contient déjà tous les axes" qu'il vaudrait mieux remplacer par "Ce projet contient tous les axes" pour éviter une confusion quand on ajoute un axe.

**Comment by anthonybocci** [comment]
J'ai remplacé le texte par "Ce projet contient tous les axes", ainsi on enlève le doute, on n'a plus peur d'avoir fait n'importe quoi en ajoutant le dernier axe.
