### ISSUE TITLE
message d'erreur quand on enlève le super administrateur de la liste des administrateur d'un axe ou d'un projet

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#18]
Quand on veut supprimer le super administrateur des administrateurs d'un axe, le message "The super administrator can\t be deleted !" s'affiche quelque soit la langue.
De plus "can't" serait mieux que "can\t".

Même souci quand on l'enlève de la liste des aministrateurs d'un projet, mais avec le message suivant : "The root can't be deleted !"

**Comment by anthonybocci** [comment]
J'ai corrigé la faute de frappe, et le message est désormais traduit pour les projets et pour les axes
