### ISSUE TITLE
type de fichier et poid qu'on peut upload dans un projet

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#19]
On ne sait pas quel format de fichier on a le droit d'upload dans un projet, il faut peut être le préciser. Et dire aussi la limite de poid du fichier.

**Comment by anthonybocci** [comment]
J'avais oublié (pas trouvé) un type mime pour les fichiers .rar maintenant c'est bon.
Je vais indiquer le type autorisé, mais pour le poids cela dépend du serveur, c'est à eux de le spécifier. On ne peut pas le dire ici.
