### ISSUE TITLE
différents problèmes pour upload des fichiers dans un projet

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#20]
-J'ai essayé d'upload un .rar de 1.21 ko et refuse en affichant : "Only zip, rar, gz granted" -> il semble mal reconnaitre les formats
-Le message cité au dessus s'est affiché en anglais alors que la langue choisie était le français
-J'ai essayé d'upload un .zip de 14 mo et il refuse en affichant le message suivant : "Le jeton CSRF est invalide. Veuillez renvoyer le formulaire." (pas de problème de langue pour ce message là)

**Comment by anthonybocci** [comment]
On peut désormais ajouter un .rar.
Mais le message "Only zip..." est mis à un endroit que je ne peux traduire.
Et en effet quand le fichier est trop gros par rapport au serveur, c'est ce message là qui se met bien que ça ne soit pas la bonne erreur.

**Comment by anthonybocci** [comment]
J'ai fini par trouver qu'il faut simplement configurer le serveur, le php.ini. Le post_max_size et upload_max_filesize pour que même tout BDTLN fonctionne.
