### ISSUE TITLE
message d'erreur quand on supprime une catégorie

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#21]
Quand on supprime une catégorie, qu'on choisit "oui" et qu'on clique sur "supprimer", on obtient une page d'erreur avec le message suivant : An exception has been thrown during the rendering of a template ("Parameter "id" for route "bdtln_user_delete_category" must match "[^/]++" ("" given) to generate a corresponding URL.") in BdtlnUserBundle:Category:delete_category.html.twig at line 13.
500 Internal Server Error - Twig_Error_Runtime
1 linked Exception: InvalidParameterException »

Mais ça fonctionne, ça supprime bien la catégorie.

**Comment by anthonybocci** [comment]
Au lieu de renvoyer vers une page je me contentais d'inclure la vue pour la catégorie en question, alors que celle-ci venait d'être supprimée. Désormais quand on supprimer une catégorie on renvoie vers la liste des catégories.
