### ISSUE TITLE
dropbox inutile en mode non connecté ?

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#26]
Quand on consulte le site sans être connecté, sur le menu il y a une dropbox pour "axes/projets" avec un seul choix dedans, ce qui semble un peu redondant.

**Comment by anthonybocci** [comment]
C'est peut-être un peu redondans (et encore), mais si on ajoute autre chose ce sera plus simple. Sauf si on fait la liste déroulante au survole.

**Comment by anthonybocci** [comment]
Désormais les listes se déroulent au passage de la souris, ainsi ce n'est plus génant même s'il n'y a qu'un seul élément dans la liste.
