### ISSUE TITLE
problème de langue dropbox en mode connecté

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#27]
Quand on est connecté en admin admin et qu'on clique sur "axes/projects" en anglais, le choix du haut dans la dropbox "liste des axes/projets" reste en français. Pas sur que ce soit tres clair j'explique pas super bien, demande moi si tu comprends pas

**Comment by anthonybocci** [comment]
Je vois, le texte "liste des Axes/Projets" n'étais pas traduit. C'est corrigé.
