### ISSUE TITLE
le bouton "back" change la langue

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#28]
Si par exemple je suis en français, je vais sur "ajouter un axe", puis je passe en anglais, et quand j'utilise le bouton "back" ça me ramène sur l'accueil, mais en français.

**Comment by anthonybocci** [comment]
Pour toutes les pages où il y a un bouton Back j'ai fait en sorte que ça renvoie directement vers l'axe ou le projet en question, en revanche pour ces deux formulaires là je vais faire en sorte que le bouton renvoie vers la liste des axes/projets
