### ISSUE TITLE
agencement de l'espace pour modifier son profil non optimal

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#30]
-les cadres pour les biographies française et anglaise sont très petits
-"prénom" est au dessus du champ alors que "nom" est à gauche du champ (uniquement connecté avec user user, pas avec admin admin)
-si j'agrandis le cadre pour la biographie en français, une partie est cachée par le cadre pour l'anglais ainsi que je bouton "soumettre" qui passe derrière et deviens donc invisible

**Comment by anthonybocci** [comment]
J'ai réaligné les champs pour éditer le profil, généralement le label est au dessus du champ comme ça c'est pareil partout.
Pour les biographies, elles sont faites pour être agrandies à la verticale, c'est pour ça. C'est pas un bogue, l'utilisateur verra que c'est à la verticale qu'on le modifie.

**Comment by anthonybocci** [comment]
Pour régler le problème des biographies j'ai bloqué la largeur à 200 px. Ainsi on ne peut les modifier qu'à la verticale.
