### ISSUE TITLE
impossible d'ajouter un nouveau membre

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#31]
Quand je remplie les champs et que je clique sur "enregistrer" rien ne se passe, les deux champs des mots de passe se vident et c'est tout. Les autres champs restent remplies.

**Comment by anthonybocci** [comment]
C'est corrigé, j'avais oublié d'affiches le jeton CSRF dans le formulaire donc il croyait qu'on l'attaquait.
