### ISSUE TITLE
traduction bouton de confirmation pour la suppression d'un projet

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#4]
Quand on veut supprimer un projet/axe/administrateur d'axe, au moment de confirmer on doit cocher oui ou non, puis cliquer sur le bouton de confirmation. Or ce bouton est "ajouter" en français et "add" en anglais ce qui est l'inverse de ce qu'on fait, peut etre que "supprimer" et "delete" seraient mieux, ou meme simplement "confirmer". C'est aussi le cas pour les axes et pour la suppression d'administrateur dans un axe.

**Comment by anthonybocci** [comment]
Corrigé, pour ajouts/modifications/gestion de participants/gestion des administrateurs pour les axes, projets, le bon texte est affiché, add, delete ou update
