### ISSUE TITLE
bouton non de suppression de projet

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#5]
Quand on veut supprimer un projet/axe, on doit cocher "oui" ou "non" au moment de confirmer, or le bouton "non" supprime quand meme le projet. C'est aussi le cas pour les axes.

**Comment by anthonybocci** [comment]
Corrigé, le bouton affiche désormais "Supprimer".

**Comment by anthonybocci** [comment]
J'ai réouvert car j'avais mal lu.
Désormais le problème est corrigé, quand on dit "non" à la suppression, on est renvoyé vers ce projet.
