### ISSUE TITLE
erreur pour ajouter des membres

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#6]
une erreur quand on veut ajouter un membre qui semble indiquer une violation d'une contrainte de la base de données. Anthony signale qu'il faut redéfinir la vue car elle a été écrasée lors d'une mise à jour du bundle.

**Comment by anthonybocci** [comment]
Corrigé, j'ai redéfini le formulaire utilisateur pour y ajouter les champs nécessaires. J'ai aussi redéfini le controleur afin de gérer comme on veut le traitement.
