### ISSUE TITLE
Traductions

### ISSUE THREAD

**Issue by Cubiccl** [anthonybocci/BDTLN#7]
Certaines parties du site sont toujours en français ou en anglais (soit bug, soit non traduits) :
Toujours en anglais : Add member, Edit profile, Titre d'un axe
Toujours en français : Titre d'un projet, Page d'édition d'un axe

**Comment by anthonybocci** [comment]
Je viens de vérifier, et pour la plupart chez moi c'est fonctionnel.. Il n'y a que dans edit proile que deux champs sont en anglais only, mais pour les autres ça fonctionne.
Donc soit vérifie de nouveau, soit j'ai mal compris le problème ?

**Comment by anthonybocci** [comment]
C'est corrigé, les axe et les projets sont traduis correctement.
