### ISSUE TITLE
Changement de langue après connexion

### ISSUE THREAD

**Issue by Cubiccl** [anthonybocci/BDTLN#8]
Lorsqu'on se connecte ou se déconnecte, la langue passe en anglais, même si elle était en français auparavant.

**Comment by anthonybocci** [comment]
Lorsqu'on se déconnecte c'est pareil, mais je le laisse pour la déconnexion car c'est pas important, on se déconnecte pour partir de toute façon.
Pour le connecter on est maintenant renvoyer vers le referer (la page précédente)
