### ISSUE TITLE
erreur page de description axe avec user user

### ISSUE THREAD

**Issue by BenoitShy** [anthonybocci/BDTLN#9]
Quand je me connecte avec le compte user user, j'ai une erreur lorsque je veux consulter la page de description d'un axe : Warning: in_array() expects parameter 2 to be array, object given
500 Internal Server Error - ContextErrorException
Cette erreur n'apparait pas si connecté avec le compte admin admin

**Comment by anthonybocci** [comment]
Le soucis venait de la fonction in_array, en second paramètre je ne lui donnait pas un tableau. Et comme tout ça est dans un "ou" et bien ce code n'est executé que si on n'est pas simple utilisateur.
Problème réglé.
